# Generated by Django 3.2 on 2021-05-24 19:54

import autoslug.fields
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=blog.models.my_slug_func),
        ),
    ]
